InstallvsConfig
quynhvuongg/Prometheus pull request #2
Opened 2020-04-03 14:43 UTC by quynhvuongg

2020-04-07 02:20 UTC, vtdat requested changes
Mông má lại đi. Trả lời mấy chỗ a thắc mắc.

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +# How to Prometheus work
grammar

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +Prometheus sẽ chủ động  `pull` các  `metrics`  về qua HTTP mỗi 10s hay 30s do chúng ta thiết lập. Bản thân các service thì thường không thể tự export được các metrics cho Prometheus mà cần đến các  `
> qua HTTP

là sao nhỉ?

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +Prometheus sẽ chủ động  `pull` các  `metrics`  về qua HTTP mỗi 10s hay 30s do chúng ta thiết lập. Bản thân các service thì thường không thể tự export được các metrics cho Prometheus mà cần đến các  `
```suggestion
Prometheus sẽ chủ động  `pull` các  `metrics`  về qua HTTP mỗi 10s hay 30s do chúng ta thiết lập. Bản thân các service thì thường không thể tự export được các metrics cho Prometheus mà cần đến các  `Instrumentation/Exporter`.  
```

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +- Exporter là những app được viết cho mấy cái thông dụng như Database, Server. Chúng ta chỉ cần chạy nó và nó sẽ export các metrics thu thập được cho mình.
> cho mấy cái 

???

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +- Exporter là những app được viết cho mấy cái thông dụng như Database, Server. Chúng ta chỉ cần chạy nó và nó sẽ export các metrics thu thập được cho mình.
> Chúng ta chỉ cần chạy nó và nó sẽ export các metrics thu thập được cho mình.

tối nghĩa

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +- Instructmentation thì chỉ những client-libraries được cung cấp bởi Prometheus hoặc một bên thứ 3 nào đó, để mình cài vào ứng dụng của mình, giúp tùy biến những metrics riêng của hệ thống.
* typo

* > hoặc một bên thứ 3 nào đó
  
  wording

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +- Prometheus: chính bản thân prometheus cũng có một built-in exporter, export các metrics về service prometheus ra tại URL:  [http://prometheus.lc:9090/metrics](http://prometheus.lc:9090/metrics)
> các metrics

bản thân `metrics` đã là plural rồi

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +scrape_configs: #Một cấu hình scrape chứa chính xác endpoint để scrape
yml không support comment như thế này

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +     command: # chỉ định configure file vào đường dẫn chứa file configure
tương tự

2020-04-07 02:20 UTC, vtdat commented on Install Provssm.md
> +Step 4 : docker -compose up
typo

2020-04-07 02:20 UTC, vtdat commented on Configuration.md
> +Prometheus được cấu hình thông qua command-line flags và configure file :
chú ý trước dấu câu vd: `:` `.` `,` ... thì không có spacing nhé. Ở sau thì sẽ có.

VD: "Hôm nay là một ngày đẹp trời. Nhưng do covid nên không được ra ngoài."

2020-04-07 02:20 UTC, vtdat commented on Configuration.md
> +Prometheus có thể reload cấu hình của nó khi chạy. Nếu cấu hình mới không được định dạng tốt, các thay đổi sẽ không được áp dụng. Reload cấu hình được kích hoạt bằng cách gửi `SIGHUP` tới Prometheus
bật cờ ở đâu

2020-04-07 02:20 UTC, vtdat commented on Configuration.md
> +  command: # chỉ định configure file vào đường dẫn chứa file configure
không cmt thế này, mà cmt cũng không đúng, chỗ `command` còn làm được nhiều việc khác

2020-04-07 02:20 UTC, vtdat commented on Configuration.md
> +Check rules sử dụng promtool : sudo apt install promtool :
nếu chạy container không cần install thế này

2020-04-07 03:52 UTC, quynhvuongg commented on Configuration.md
> +  command: # chỉ định configure file vào đường dẫn chứa file configure
```yml
 # docker-compose.yml
  command:
       - "--config.file=/etc/prometheus/prometheus.yml"  # chỉ định configure file vào đường dẫn
```

2020-04-07 03:59 UTC, quynhvuongg commented on Configuration.md
> +Check rules sử dụng promtool : sudo apt install promtool :
Em cũng ko nhớ rõ đoạn đó n được gợi ý install ra sao , check lại history cũng không nhớ lại được ạ .

2020-04-07 04:15 UTC, quynhvuongg commented on Install Provssm.md
> +scrape_configs: #Một cấu hình scrape chứa chính xác endpoint để scrape
```yml
# prometheus.yml
global:  
  # Set thời gian lấy metrics sau mỗi 15s (defaul = 1m)
  scrape_interval:  15s
  #Đính kèm labels này vào bất kỳ time series hoặc alert nào khi liên lạc với hệ thống bên ngoài (remote storage , Alertmanager )
  external_labels:  
    monitor:  'my-monitor'  
#Một cấu hình scrape chứa chính xác endpoint để scrape
scrape_configs:  
  - job_name:  'prometheus'  
    static_configs:
         - targets: ['localhost:9090']
```

2020-04-07 04:22 UTC, quynhvuongg commented on Install Provssm.md
> +- Exporter là những app được viết cho mấy cái thông dụng như Database, Server. Chúng ta chỉ cần chạy nó và nó sẽ export các metrics thu thập được cho mình.
Phần này em viết có chút thừa và viết chưa được đúng lắm, xem sẽ xem lại và đặt vào phần khác thích hợp hơn .

2020-04-07 07:44 UTC, vtdat commented on Configuration.md
> +Check rules sử dụng promtool : sudo apt install promtool :
trong container của prometheus là mặc định có sẵn promtool rồi

2020-04-07 07:44 UTC, vtdat commented on Configuration.md
> +  command: # chỉ định configure file vào đường dẫn chứa file configure
ok

2020-04-07 07:44 UTC, vtdat commented on Install Provssm.md
> +- Exporter là những app được viết cho mấy cái thông dụng như Database, Server. Chúng ta chỉ cần chạy nó và nó sẽ export các metrics thu thập được cho mình.
ok

2020-04-10 08:16 UTC, vtdat requested changes
Chú ý Headings https://www.markdownguide.org/basic-syntax/#headings

Sửa lại

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +  # metrics_path defaults to '/metrics'
??

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +       - "--config.file=/etc/prometheus/prometheus.yml"  # chỉ định configure file vào đường dẫn
vẫn inline comment thế này à

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +*_Alerting rules_*
Emphasis thì bôi đậm đi

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +```
format lại tử tế

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +# Cảnh báo cho bất kì instance không tới được trong 2m
hơi tối nghĩa? thế nào là instance không tới được?

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +*_Inspecting alerts during runtime_*
tương tự, bôi đậm, in nghiêng thế này dễ xót mà ko nhấn mạnh được

2020-04-10 08:16 UTC, vtdat commented on Configuration.md
> +*_Sending alert notifications_*
tương tự, bôi đậm, in nghiêng thế này dễ xót mà ko nhấn mạnh được

https://www.markdownguide.org/basic-syntax/#headings

2020-04-10 08:19 UTC, vtdat commented
Alertmanager nữa?

2020-04-10 09:11 UTC, quynhvuongg commented on Configuration.md
> +```
```yml
# prometheus.yml
global:

# Set thời gian lấy metrics sau mỗi 15s (defaul = 1m)
  scrape_interval:  15s

#Đính kèm labels này vào bất kỳ time series
#hoặc alert nào khi liên lạc với hệ thống
#bên ngoài(remote storage, Alertmanager)
  external_labels:  
    monitor:  'my-monitor'  

#Một cấu hình scrape chứa chính xác endpoint để scrape
scrape_configs:  
  - job_name:  'prometheus'  
    static_configs:
         - targets: ['localhost:9090']
  
```

2020-04-10 09:15 UTC, quynhvuongg commented on Configuration.md
> +# Cảnh báo cho bất kì instance không tới được trong 2m
```yml
# Cảnh báo cho service nào không hoạt động
  - alert: service_down  #tên của alert
    expr: up == 0        #biểu thức đánh giá
    for: 2m   #thời gian chờ trước khi kích hoạt cảnh báo
```

2020-04-13 10:37 UTC, vtdat approved these changes
ok

2020-04-13 13:06 UTC, merged