ConfigurationFiles
quynhvuongg/Prometheus pull request #3
Opened 2020-04-07 01:25 UTC by quynhvuongg

2020-04-07 02:24 UTC, vtdat reviewed
ok rồi. viết thêm 1 service cho cadvisor rồi visual lên grafana.

demo 1 cái cảnh báo xem nào.

update kết quả vào 1 file khác

2020-04-07 02:51 UTC, quynhvuongg commented
Vâng a

2020-04-07 10:01 UTC, quynhvuongg commented
Em up file kết quả ạ

2020-04-10 08:18 UTC, vtdat requested changes
phần này ok rồi

2020-04-10 08:18 UTC, vtdat commented on ConfigurationFiles/docker-compose.yml
> +    - cadvisor
tại sao?

2020-04-10 08:19 UTC, vtdat approved these changes

2020-04-10 08:35 UTC, quynhvuongg commented on ConfigurationFiles/docker-compose.yml
> +    - cadvisor
Vì CAd exports metrics liên quan đến containers nên em muốn chạy được trước.

2020-04-13 10:36 UTC, vtdat commented on ConfigurationFiles/docker-compose.yml
> +    - cadvisor
ok merge phần này đi

2020-04-13 13:05 UTC, merged