Servicediscovery - Storage - Exporters
quynhvuongg/Prometheus pull request #7
Opened 2020-04-17 06:42 UTC by quynhvuongg

@vtdat

2020-04-20 10:10 UTC, vtdat requested changes
ok thêm phần so sánh giữa local storage với remote storage

2020-04-21 04:48 UTC, quynhvuongg commented
### Compare local and remote storage

**_Local Storage_**

* Dữ liệu được lưu theo định dạng TSDB trên disk(SSD/HDD)
* Hỗ trợ WAL và lưu trữ khối dữ liệu trong 2 giờ
* Không có khả năng mở rộng và độ bền kém
* Được sử dụng cho việc đánh giá các quy tắc alert hoặc record
* Không lưu trữ lâu dài

**_Remote Storage_**

* Dữ liệu được ghi thông qua các bộ điều hợp lưu trữ và Prometheus không kiểm soát định dạng lưu trữ dữ liệu,được tùy chỉnh
* Dữ liệu được hợp nhất với lưu trữ cục bộ
* Hỗ trợ relabeling và hạn chế số liệu ghi tối thiểu
* Có khả năng mở rộng và lưu trữ lâu dài
* Tất cả các đánh giá PromQL trên dữ liệu thô vẫn xảy ra trong chính Prometheus. Điều này có nghĩa là các truy vấn đọc từ xa có một số giới hạn về khả năng mở rộng, vì tất cả dữ liệu cần thiết cần được tải vào máy chủ Prometheus truy vấn trước rồi xử lý ở đó.

----------------------------
Anh giúp em nhận xét với ạ.

2020-04-22 07:09 UTC, vtdat commented
> ### Compare local and remote storage
> **_Local Storage_**
> 
> * Dữ liệu được lưu theo định dạng TSDB trên disk(SSD/HDD)
> * Hỗ trợ WAL và lưu trữ khối dữ liệu trong 2 giờ
> * Không có khả năng mở rộng và độ bền kém
> * Được sử dụng cho việc đánh giá các quy tắc alert hoặc record
> * Không lưu trữ lâu dài
> 
> **_Remote Storage_**
> 
> * Dữ liệu được ghi thông qua các bộ điều hợp lưu trữ và Prometheus không kiểm soát định dạng lưu trữ dữ liệu,được tùy chỉnh
> * Dữ liệu được hợp nhất với lưu trữ cục bộ
> * Hỗ trợ relabeling và hạn chế số liệu ghi tối thiểu
> * Có khả năng mở rộng và lưu trữ lâu dài
> * Tất cả các đánh giá PromQL trên dữ liệu thô vẫn xảy ra trong chính Prometheus. Điều này có nghĩa là các truy vấn đọc từ xa có một số giới hạn về khả năng mở rộng, vì tất cả dữ liệu cần thiết cần được tải vào máy chủ Prometheus truy vấn trước rồi xử lý ở đó.
> 
> Anh giúp em nhận xét với ạ.

chưa nổi bật được sự khác nhau.

sử dụng local storage thì ko relabel được ah?

2020-04-22 08:57 UTC, quynhvuongg commented
### Compare local and remote storage

**_Local Storage_**

* Dữ liệu được lưu theo định dạng TSDB trên disk(SSD/HDD)
* Không có khả năng mở rộng và độ bền kém
* Không lưu trữ lâu dài (mặc định 15d)
* Không có tính sẵn sàng cao
* Độ khả dụng phụ thuộc và disk

**_Remote Storage_**

* Dữ liệu được ghi thông qua các bộ điều hợp lưu trữ và Prometheus không kiểm soát định dạng lưu trữ dữ liệu,được tùy chỉnh
* Có khả năng mở rộng linh hoạt và lưu trữ lâu dài
* Độ khả dụng lớn
* Tất cả các đánh giá PromQL trên dữ liệu thô vẫn xảy ra trong chính Prometheus. Điều này có nghĩa là các truy vấn đọc từ xa có một số giới hạn về khả năng mở rộng, vì tất cả dữ liệu cần thiết cần được tải vào máy chủ Prometheus truy vấn trước rồi xử lý ở đó.

2020-05-11 01:52 UTC, vtdat approved these changes
> ### Compare local and remote storage
> **_Local Storage_**
> 
> * Dữ liệu được lưu theo định dạng TSDB trên disk (SSD/HDD)
> * Không có khả năng mở rộng và độ bền kém
> * Không lưu trữ lâu dài (mặc định 15d)
> * Không có tính sẵn sàng cao
> * Độ khả dụng phụ thuộc và disk
> * Có thể sử dụng PromQL để truy vấn và đánh giá các rule đối với dữ liệu trên local
> 
> **_Remote Storage_**
> 
> * Dữ liệu được ghi thông qua các bộ điều hợp lưu trữ và Prometheus không kiểm soát định dạng lưu trữ dữ liệu,được tùy chỉnh
> * Có khả năng mở rộng linh hoạt và lưu trữ lâu dài
> * Độ khả dụng lớn
> * Chỉ có thể sử dụng Prometheus để truy vấn , không được sử dụng dữ liệu trên lưu trữ remote để đánh giá các rule
> * Tất cả các đánh giá PromQL trên dữ liệu thô vẫn xảy ra trong chính Prometheus. Điều này có nghĩa là các truy vấn đọc từ xa có một số giới hạn về khả năng mở rộng, vì tất cả dữ liệu cần thiết cần được tải vào máy chủ Prometheus truy vấn trước rồi xử lý ở đó.

OK bổ sung phần so sánh rồi merge thôi

2020-05-11 17:25 UTC, merged